django_server/django_server/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf.urls import url, include,re_path
from health_team import views
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Site
    url(r'^$', views.table, name='index'),
    url(r'^table.html$', views.table, name='table'),
    url(r'^blank-1.html$', views.cadastroPaciente, name='cadastroPaciente'),
    url(r'^estatisticas.html$', views.estats, name='estatisticas'),
    url(r'^dailycontrolCSV$', views.downloadDaily, name='dailycontrolCSV'),
    url(r'^barreirasCSV$', views.downloadBarreiras, name='barreirasCSV'),
    url(r'^AsthmaControlQuestionnaireCSV$', views.downloadAsthmaControlQuestionnaire, name='AsthmaControlQuestionnaireCSV'),
    url(r'^UserProfileInfoCSV$', views.downloadUserProfileInfo, name='downloadUserProfileInfoCSV'),
    url(r'^FitBitDataCSV$', views.downloadFitBitData, name='downloadFitBitDataCSV'),
    url(r'^app$', views.downloadAPK, name='downloadAPK'),
    url(r'^404$', views.erro_404, name='erro_404'), 
    # Uso Interno 
    re_path(r'^favicon\.ico$', favicon_view),
    #url(r'^2$', views.index, name='index2'),
    url(r'^special/', views.special, name='special'),
    url(r'^health_team/', include('health_team.urls')),
    url(r'^rest/', include('server.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

django_server/health_team/urls.py
from django.conf.urls import url
from django.urls import  path
from health_team import views

# SET THE NAMESPACE!
app_name = 'health_team'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns = [
    #url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_login/forgot-password.html$', views.forgot_password, name='forgot_password'),
    url(r'^user_login/register.html$', views.register_account, name='register_account'),
    #url(r'^user_login/register2.html$', views.register_account2, name='register_account2'),
    url(r'^table.html$', views.table, name='table'),
    url(r'^blank-1.html$', views.cadastroPaciente, name='cadastroPaciente'),
    
    path('graphs/<slug:username>', views.pacienteGraficos2, name='table_test2'),
    path('metas/<slug:username>', views.pageMetas, name='metas'),

]

django_server/server/urls.py
# from rest_framework import routers
from rest_framework_simplejwt import views as jwt_views
from django.urls import path, include
from server import views

# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path('token/', jwt_views.TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('token/refresh/',
         jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('teste/', views.Test.as_view(), name='teste'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('user_data/', views.UserData.as_view(), name='user_data'),
    path('change_password/', views.UserData.as_view(), name='change_password'),
    path('questionnaire/', views.Questionnaire.as_view(), name='questionnaire'),
    path('daily/', views.Daily.as_view(), name='daily'),
    path('fitbit/', views.Fitbit.as_view(), name="fitbit"),
    path('fitbit/login/', views.FitbitLogin.as_view(), name='fitbit_login'),
    path('fitbit/auth/', views.FitbitAuth.as_view(), name='fitbit_auth'),
    path('goals/', views.Goals.as_view(), name="goals"),
    path('exercises/', views.Exercises.as_view(), name="exercises"),
    path('milestones/', views.Milestones.as_view(), name="milestones"),
    path('barriers/', views.Barriers.as_view(), name="barriers"),
    path('watson/', views.Watson.as_view(), name="watson"),
    path('faq/', views.Faq.as_view(), name="FAQ"),
]

django_server/health_team/models.py
from server.models import User, UserProfileInfo, AsthmaControlQuestionnaire, FitbitFile, DailyControl, PracticeBarriers, Goal

django_server/health_team/forms.py
from django import forms
from health_team.models import User, UserProfileInfo, AsthmaControlQuestionnaire, FitbitFile, Goal


class GoalForm(forms.ModelForm):
    class Meta():
        model = Goal
        fields = ('activity', 'quantity', 'unit', 'startDate', 'endDate')
        widgets = {
            'activity': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control form-control-user'}),
            'unit': forms.TextInput(attrs={'class': 'form-control form-control-user','value':'passos'}),
            'startDate': forms.DateInput(attrs={'class': 'form-control form-control-user','type':'date'}),
            'endDate': forms.DateInput(attrs={'class': 'form-control form-control-user','type':'date'})
            
        }
        
        


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user'}))

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-user'}),
            
        }

class UserFormForProfile(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user'}))

    class Meta():
        model = User
        labels = {
        "username": "CPF"
        }
        fields = ('username', 'email', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-user'}),
            
        }


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('nome', 'sobrenome', 'rg', 'altura', 'peso',
                  'telefone', 'token','nascimento')

        labels = {
        "token": "RGHC"
        }


        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'sobrenome': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'rg': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'altura': forms.TextInput(attrs={'class': 'form-control form-control-user','placeholder':"1.60"}),
            'peso': forms.TextInput(attrs={'class': 'form-control form-control-user','placeholder':"40"}),
            'telefone': forms.NumberInput(attrs={'class': 'form-control form-control-user','type':'tel'}),
            'token': forms.TextInput(attrs={'class': 'form-control form-control-user'}),
            'nascimento': forms.DateInput(attrs={'class': 'form-control form-control-user','type':'date'}),        
        }

django_server/health_team/views.py
from django.shortcuts import render
from health_team.forms import UserForm, UserProfileInfoForm, UserFormForProfile, GoalForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings

from plotly.offline import plot
from plotly.graph_objs import Scatter
from plotly.graph_objs import Line
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np
import pandas as pd
import datetime
import time
import traceback
import csv
import os

from server.handleUserData import getFitbitData

from server.models import User, UserProfileInfo, AsthmaControlQuestionnaire, FitbitFile, DailyControl, PracticeBarriers,FitbitProfile,Goal

def index(request):
    return render(request, 'health_team/index.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'health_team/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('table'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'health_team/login.html', {})

def forgot_password(request):
    return render(request, 'health_team/forgot-password.html', {})

def register_account2(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
    

    return render(request, 'health_team/register.html', {})

def register_account(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        print(dir(user_form))
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
            new_user = authenticate(username=user_form.cleaned_data['username'],
                                    password=user_form.cleaned_data['password'],
                                    )
            login(request, new_user)
            return HttpResponseRedirect(reverse('table'))
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()
    return render(request, 'health_team/register2.html',
                  {'user_form': user_form,
                   'registered': registered})
    #return render(request, 'health_team/register.html', {})

def erro_404(request):
    return render(request, 'health_team/404_error.html', {})

@login_required
def table(request):
    lista = UserProfileInfo.objects.all()
    print(len(lista))
    return render(request, 'logged/table2.html', {'lista':lista})





@login_required
def cadastroPaciente(request):
    registered = False
    if request.method == 'POST':
        user_form = UserFormForProfile(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            #print(user)
            profile = profile_form.save(commit=False)
            profile.user = user
            print(user)
            profile.save()
            registered = True
            return HttpResponseRedirect(reverse('table'))
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserFormForProfile()
        profile_form = UserProfileInfoForm()
    return render(request, 'logged/blank-12.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})
    #return render(request, 'logged/blank-12.html', {})



@login_required
def pacienteGraficos2(request,username):
    #https://www.youtube.com/watch?v=vCX6Tpb9sP8
    #https://www.youtube.com/watch?v=B4Vmm3yZPgc
    #https://stackoverflow.com/questions/55832576/how-to-integrate-chart-js-in-django
    #https://www.codingwithricky.com/2019/08/28/easy-django-plotly/

    #print((UserProfileInfo.objects))

    #asthmaQuestionaire = AsthmaControlQuestionnaire.objects.get_or_create(id=username)
    user_data = UserProfileInfo.objects.get(user_id=username)
    print(user_data.user, user_data.user_id, UserProfileInfo.objects.get(user_id=username).user_id)
    try:
        listaData = []
        listaTosse = []
        listaChiado = []
        listaFaltaDeAr = []
        listaAcordar = []
        listaBombinha = []
        listaPico1 = []
        listaPico2 = []
        listaPico3 = []
        listaNotes = []
        dailycontrol = DailyControl.objects.all().filter(user_id=username)
        if len(dailycontrol)!=0:
            for day in dailycontrol:
                print("Certo")
                listaData.append(day.date.strftime("%Y-%m-%d"))
                listaTosse.append(int(day.tosse))
                listaChiado.append(int(day.chiado))
                listaFaltaDeAr.append(int(day.faltaDeAr))
                listaAcordar.append(int(day.acordar))
                listaBombinha.append(int(day.bombinha))
                listaPico1.append(day.pico1)
                listaPico2.append(day.pico2)
                listaPico3.append(day.pico3)
                listaNotes.append(day.notes)
        else:
            print("Errado")
            listaData = ["0000-00-00"]
            listaTosse = [False]
            listaChiado = [False]
            listaFaltaDeAr = [False]
            listaAcordar = [False]
            listaBombinha = [False] 
            listaPico1 = [0]
            listaPico2 = [0]
            listaPico3 = [0]
            listaNotes = ["No data"]


    except:
        print("Errado2")
        listaData = ["0000-00-00"]
        listaTosse = [False]
        listaChiado = [False]
        listaFaltaDeAr = [False]
        listaAcordar = [False]
        listaBombinha = [False]
        listaPico1 = [0]
        listaPico2 = [0]
        listaPico3 = [0]
        listaNotes = ["Fail to load Data"]

    try:
        listaquestion1 = []
        listaquestion2 = []
        listaquestion3 = []
        listaquestion4 = []
        listaquestion5 = []
        listaquestion6 = []
        listaquestion7 = []
        listaData2 = []

        questionario = AsthmaControlQuestionnaire.objects.all().filter(user_id=username)
        if len(questionario)!=0:
            for day in questionario:
                print("Certo - Questionario")
                listaData2.append(day.date.strftime("%Y-%m-%d"))
                listaquestion1.append(day.question1)
                listaquestion2.append(day.question2)
                listaquestion3.append(day.question3)
                listaquestion4.append(day.question4)
                listaquestion5.append(day.question5)
                listaquestion6.append(day.question6)
                listaquestion7.append(day.question7)

        else:
            print("Errado")
            listaquestion1 = [0]
            listaquestion2 = [0]
            listaquestion3 = [0]
            listaquestion4 = [0]
            listaquestion5 = [0]
            listaquestion6 = [0]
            listaquestion7 = [0]
            listaData2 = ["0000-00-00"]


    except:
        listaquestion1 = [0]
        listaquestion2 = [0]
        listaquestion3 = [0]
        listaquestion4 = [0]
        listaquestion5 = [0]
        listaquestion6 = [0]
        listaquestion7 = [0]
        listaData2 = ["0000-00-00"]

    try:
        listaInteresse = []
        listaTempo = []
        listaEnergia = []
        listaFaltaAr = []
        listaCompanhia = []
        listaDinheiro = []
        listaCoisa = []
        listaSeguranca = []
        listaClima = []
        listaEquipamentos = []
        listaDate3 = []

        barreiras_list = PracticeBarriers.objects.all().filter(user_id=username)
        if len(barreiras_list)!=0:
            for barreiras in barreiras_list:

                if barreiras.interesse != None:
                    listaInteresse.append(barreiras.interesse)
                else:
                    listaInteresse.append('0')
                
                if barreiras.tempo != None:
                    listaTempo.append(barreiras.tempo)
                else:
                    listaTempo.append('0')

                if barreiras.energia != None:
                    listaEnergia.append(barreiras.energia)
                else:
                    listaEnergia.append('0')

django_server/templates/health_team/404_error.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Profile - Brand</title>
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="/static/assets/fonts/fontawesome-all.min.css">
        <link rel="stylesheet" href="/static/assets/css/styles.min.css">
    </head>

<body class="text-center d-xl-flex align-items-center align-content-center align-self-center align-items-xl-center d-flex justify-content-center align-items-center jumbotron d-flex align-items-center">
    <div class="text-center">
        <div class="error mx-auto" data-text="404">
            <p class="m-0">404</p>
        </div>
        <p class="text-dark mb-5 lead">Página não encontrada</p>
        <p class="text-black-50 mb-0">Algo de errado aconteceu!</p><a href="/">← Voltar para o inicio</a></div>
    <script src="/static/assets/js/jquery.min.js"></script>
    <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="/static/assets/js/script.min.js"></script>
</body>

</html>

django_server/templates/health_team/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Asma HC</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">{# Home Link / Register Link#}
                <li><a class="navbar-brand" href="{% url 'index' %}">Gerenciador Asma</a></li>
                <li><a class="navbar-link" href="{% url 'health_team:register' %}">Register</a></li>
                {# Some logic on what to display for last item#}
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'health_team:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

django_server/templates/health_team/fitbit_login.html
<form method="POST" role="form">
    {% csrf_token %}
    <div class="tab-content">
        <div class="tab-pane active" role="tabpanel" id="step1">
            <div class="mobile-grids">
                <div class="mobile-right">
                    {% block includes %}
                    <h4>{{ message }}</h4>
                    {% endblock includes %}
                    <input type="text" name="cpf_number" class="cpf-text" value="">
                    <input type="submit" value="submit" />
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</form>

django_server/templates/health_team/fitbit_login_layout.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Fitbit Integração</title>
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="/static/assets/fonts/fontawesome-all.min.css">
        <link rel="stylesheet" href="/static/assets/css/styles.min.css">
    </head>

<body class="bg-gradient-primary jumbotron d-flex align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 col-lg-12">
                                <div class="p-5">
                                    <form form method="POST" role="form">
                                        {% csrf_token %}
                                        {% block includes %}
                                        <div class="text-center">
                                            <h4 class="text-dark mb-2">{{ message }}</h4>
                                        </div>
                                        {% endblock includes %}
                                        <div class="form-group"><input class="form-control form-control-user" type="text" aria-describedby="emailHelp" placeholder="CPF - 00000000000" name="cpf_number"></div><button class="btn btn-primary btn-block text-white btn-user"
                                            type="submit" value="submit">Confirmar</button></form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/assets/js/jquery.min.js"></script>
    <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="/static/assets/js/script.min.js"></script>
</body>

</html>

django_server/templates/health_team/forgot-password.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Forgot password</title>
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
        <link rel="stylesheet" href="/static/assets/fonts/fontawesome-all.min.css">
        <link rel="stylesheet" href="/static/assets/css/styles.min.css">
    </head>

<body class="bg-gradient-primary jumbotron d-flex align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-2">Esqueceu sua senha?</h4>
                                        <p class="mb-4">Sem problemas. Iremos enviar um email para você reiniciar sua senha!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Qual o seu email cadastrado? - Não habilitado" name="email" disabled></div>
                                        <button class="btn btn-primary btn-block text-white btn-user" type="submit" disabled>Redefinir Senha</button></form>
                                    <div class="text-center">
                                        <hr><a class="small" href="register.html">Cria uma conta!</a></div>
                                    <div class="text-center"><a class="small" href="/health_team/user_login/">Já tem uma conta? Logue nela!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="/static/assets/js/jquery.min.js"></script>
    <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/assets/js/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="/static/assets/js/script.min.js"></script>
</body>

</html>

django_server/templates/health_team/index.html
{% extends "health_team/base.html" %}
{% block body_block %}<div class="container">
    <div class="jumbotron">
        <h1>Bem vindo ao Asma App</h1>
        {% if user.is_authenticated %}
        <h2>Olá {{ user.username }}</h2>
        {% else %}
        <h2>Se cadastre ou faça login para continuar</h2>
        {% endif %}
    </div>
</div>{% endblock %}

django_server/templates/health_team/login.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Table - Brand</title>
    <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="/static/assets/fonts/fontawesome-all.min.css">
    <link rel="stylesheet" href="/static/assets/css/styles.min.css">
</head>

<body class="bg-gradient-primary jumbotron vertical-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h4 class="text-dark mb-4">Seja bem vindo!</h4>
                                    </div>
                                    <form class="user" method="post" action="{% url 'health_team:user_login' %}">
                                        {% csrf_token %}
                                        {# A more "HTML" way of creating the login form#}
                                        <div class="form-group"><input class="form-control form-control-user" type="text" id="username" placeholder="Digite seu usuário" name="username"></div>
                                        <div class="form-group"><input class="form-control form-control-user" type="password" id="exampleInputPassword" placeholder="Digite sua senha" name="password"></div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <div class="form-check"><input class="form-check-input custom-control-input" type="checkbox" id="formCheck-1"><label class="form-check-label custom-control-label" for="formCheck-1">Remember Me</label></div>
                                            </div>
                                        </div><button class="btn btn-primary btn-block text-white btn-user" type="submit" name="" value="Login">Logar</button>
                                        <hr>
                                    </form>
                                    <div class="text-center"><a class="small" href="forgot-password.html">Esqueceu a senha?</a></div>
                                        <div class="text-center"><a class="small" href="register.html">Criar uma nova conta!</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="assets/js/script.min.js"></script>
</body>

</html>

django_server/templates/health_team/login3.html
{% extends 'health_team/base.html' %}
{% block body_block %}
<div class="container">
    <div class="jumbotron">
        <h1>Faça o login aqui:</h1>
        <form method="post" action="{% url 'health_team:user_login' %}">
            {% csrf_token %}
            {# A more "HTML" way of creating the login form#}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="User">
            <label for="password">Senha:</label>
            <input type="password" name="password" placeholder="Senha"><input type="submit" name="" value="Login">
        </form>
    </div>
</div>
{% endblock %}

django_server/templates/health_team/registration.html
{% extends "health_team/base.html" %}
{% load static %}{% block body_block %}
<div class="container">
    <div class="jumbotron">
        {% if registered %}
        <h1>Obrigado por se cadastrar!</h1>
        {% else %}
        <h1>Cadastre-se aqui</h1>
        <h3>Complete os campos.</h3>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Cadastrar">
        </form>

        {% endif %}
    </div>
</div>
{% endblock %}